In [1]:
import numpy as np

## DataTypes & Attributes
- NumPy's main datatype is `ndarray`

In [2]:
a1 = np.array([1,2,3])
a1, a1.ndim, a1.shape

(array([1, 2, 3]), 1, (3,))

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2, a2.ndim, a2.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 2,
 (3, 3))

## Anantomy of a NumPy array
![.](./numpy_anatomy.png)

In [5]:
a3 = np.array(
    [
        [[1,2,3], [4,5,6]],
        [[7,8,9], [10,11,12]],
        [[13,14,15], [16,17,18]]
    ]
    )
a3, a3.ndim, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 3,
 (3, 2, 3))

In [6]:
a1.size, a2.size, a3.size

(3, 9, 18)

In [7]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [9]:
# Create a DataFrame from a NumPy array
import pandas as pd

df2 = pd.DataFrame(a2)
df2

,0,1,2
0,1,2,3
1,4,5,6
2,7,8,9


In [10]:
df3 = pd.DataFrame(a3)
# A dataframe can not be created from a 3D or higher DataFrame

ValueError: Must pass 2-d input. shape=(3, 2, 3)

## Creating NumPy Array

In [28]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [29]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
type(ones)

numpy.ndarray

In [30]:
zeros = np.zeros((2,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
random_array = np.random.randint(0, 10, size=(2,3))
random_array

array([[2, 8, 3],
       [1, 9, 5]], dtype=int32)

In [ ]:
random2 = np.random.random((3, 5))
random2

array([[0.80280685, 0.9157117 , 0.55780739, 0.45209327, 0.93790596],
       [0.08285192, 0.77333446, 0.37877623, 0.7342101 , 0.17950002],
       [0.41142858, 0.96051914, 0.53043753, 0.86804766, 0.35109766]])

In [12]:
# Pseudo-random numbers
np.random.seed(2)
random3 = np.random.randint(0, 10, size=(3,5))
random3

array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6]], dtype=int32)

## 3. Viewing arrays and matrices

In [20]:
# find the unique numbers from an array/matrix
np.unique(random3)

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [21]:
a1

array([1, 2, 3])

In [22]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [24]:
a1[0]

np.int64(1)

In [25]:
a2[0]

array([1, 2, 3])

In [26]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

[NumPy's Axis & Dimension explained](https://www.youtube.com/watch?v=XC_j0cr_a8U)

## 4. Manipulate & Compare Arrays

### Arithmetic
Basic math equations

In [32]:
a1

array([1, 2, 3])

In [33]:
ones = np.ones(shape=3)

In [34]:
ones

array([1., 1., 1.])

In [35]:
a1 + ones

array([2., 3., 4.])

In [36]:
a1*ones

array([1., 2., 3.])

In [37]:
random = np.random.randint(0, 10, size=3)
random

array([4, 3, 7], dtype=int32)

In [38]:
random + a1

array([ 5,  5, 10])

In [43]:
random2 = np.random.randint(0, 10, size=(2,3))
random2, a1

(array([[2, 4, 1],
        [7, 8, 2]], dtype=int32),
 array([1, 2, 3]))

In [44]:
random2 + a1

array([[ 3,  6,  4],
       [ 8, 10,  5]])

In [47]:
# Modulo, get the remainder
random2 % a1, np.mod(random2, a1)

(array([[0, 0, 1],
        [0, 0, 2]]),
 array([[0, 0, 1],
        [0, 0, 2]]))

In [46]:
#  Floor division removes the decimals (rounds down)
random2 // a1, np.floor_divide(random2, a1)

(array([[2, 2, 0],
        [7, 4, 0]]),
 array([[2, 2, 0],
        [7, 4, 0]]))

### NumPy uses broadcasting to make everything faster
- Broadcasting: how numpy treats arrays with different shapes during arithmetic operations
- Broadcast the smaller array across the bigger one
- NumPy compares shapes element-wise
- 2 2D arrays are compatible when:
    - They are equal, or
    - One of them is 1
