In [1]:
import numpy as np

## DataTypes & Attributes
- NumPy's main datatype is `ndarray`

In [13]:
a1 = np.array([1,2,3])
a1, a1.ndim, a1.shape

(array([1, 2, 3]), 1, (3,))

In [ ]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2, a2.ndim, a2.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 2,
 (3, 3))

## Anantomy of a NumPy array
![.](./numpy_anatomy.png)

In [15]:
a3 = np.array(
    [
        [[1,2,3], [4,5,6]],
        [[7,8,9], [10,11,12]],
        [[13,14,15], [16,17,18]]
    ]
    )
a3, a3.ndim, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 3,
 (3, 2, 3))

In [16]:
a1.size, a2.size, a3.size

(3, 9, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [21]:
# Create a DataFrame from a NumPy array
import pandas as pd

df2 = pd.DataFrame(a2)
df2

,0,1,2
0,1,2,3
1,4,5,6
2,7,8,9


In [ ]:
df3 = pd.DataFrame(a3)
# A dataframe can not be created from a 3D or higher DataFrame

ValueError: Must pass 2-d input. shape=(3, 2, 3)