In [1]:
import numpy as np

## DataTypes & Attributes
- NumPy's main datatype is `ndarray`

In [13]:
a1 = np.array([1,2,3])
a1, a1.ndim, a1.shape

(array([1, 2, 3]), 1, (3,))

In [ ]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2, a2.ndim, a2.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 2,
 (3, 3))

## Anantomy of a NumPy array
![.](./numpy_anatomy.png)

In [15]:
a3 = np.array(
    [
        [[1,2,3], [4,5,6]],
        [[7,8,9], [10,11,12]],
        [[13,14,15], [16,17,18]]
    ]
    )
a3, a3.ndim, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 3,
 (3, 2, 3))

In [16]:
a1.size, a2.size, a3.size

(3, 9, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [21]:
# Create a DataFrame from a NumPy array
import pandas as pd

df2 = pd.DataFrame(a2)
df2

,0,1,2
0,1,2,3
1,4,5,6
2,7,8,9


In [ ]:
df3 = pd.DataFrame(a3)
# A dataframe can not be created from a 3D or higher DataFrame

ValueError: Must pass 2-d input. shape=(3, 2, 3)

## Creating NumPy Array

In [23]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [24]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [27]:
zeros = np.zeros((2,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size=(2,3))
random_array

array([[2, 8, 3],
       [1, 9, 5]], dtype=int32)

In [32]:
random2 = np.random.random((3, 5))
random2

array([[0.80280685, 0.9157117 , 0.55780739, 0.45209327, 0.93790596],
       [0.08285192, 0.77333446, 0.37877623, 0.7342101 , 0.17950002],
       [0.41142858, 0.96051914, 0.53043753, 0.86804766, 0.35109766]])

In [ ]:
# Pseudo-random numbers
np.random.seed(2)
